/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PiWTMw87aX8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Textarea } from "@/components/ui/textarea";

export function Appointment() {
  //initial form
  // const startingData = {
  //   name: "",
  //   surname: "",
  //   phone: 1,
  //   date: 0,
  //   time: "not started",
  // };
  // const [formData, setFormData] = useState(startingData);

  const [name, setName] = useState("");
  const [surname, setSurname] = useState("");
  const [phone, setPhone] = useState("");
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("Appointment request: ", { name, surname, phone, date, time });
    const options = {
      method: "POST",
      body: JSON.stringify({ name, surname, phone, date, time }),
      "content-type": "application/json",
    };
    const res = await fetch("http://localhost:3001/api/obtenerTurno", options);
  };

  const scrollToSection = () => {
    const section = document.getElementById("appointment");
    if (section) {
      section.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-[#0077B6] text-white">
        <Link
          href="#"
          className="flex items-center justify-center"
          prefetch={false}
        >
          <SmileIcon className="h-6 w-6" />
          <span className="sr-only">Acme Dental</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            About
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Services
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Testimonials
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-white">
          <div className="container px-4 md:px-6 grid gap-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Dr. Jane Doe, DMD
              </h1>
              <p className="text-lg">
                Experienced Dentist Specializing in Cosmetic Dentistry
              </p>
              <p>
                Welcome to our dental practice! I'm Dr. Jane Doe, and I'm
                passionate about helping my patients achieve beautiful, healthy
                smiles. With over 15 years of experience in the field of
                cosmetic dentistry, I provide personalized care and the latest
                treatments to ensure your dental needs are met.
              </p>
              <Button
                onClick={scrollToSection}
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#00B894] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#00a382] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 animate-pulse"
              >
                Schedule an Appointment
              </Button>
            </div>
            <img
              src="/placeholder.svg"
              width="550"
              height="550"
              alt="Dr. Jane Doe"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full"
            />
          </div>
        </section>

        <section
          id="appointment"
          className="w-full py-12 md:py-24 lg:py-32 bg-[#F5F5F5] min-h-[100dvh]"
        >
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Schedule an Appointment
                </h2>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form onSubmit={handleSubmit} className="flex flex-col gap-2">
                  <div className="grid grid-cols-2 gap-2">
                    <Input
                      type="text"
                      placeholder="Name"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      className="flex-1"
                    />
                    <Input
                      type="text"
                      placeholder="Surname"
                      value={surname}
                      onChange={(e) => setSurname(e.target.value)}
                      className="flex-1"
                    />
                  </div>
                  <Input
                    type="tel"
                    placeholder="Phone"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    className="max-w-lg flex-1"
                  />
                  <div className="grid grid-cols-2 gap-2">
                    <Input
                      type="date"
                      value={date}
                      onChange={(e) => setDate(e.target.value)}
                      className="flex-1"
                    />
                    <Input
                      type="time"
                      value={time}
                      onChange={(e) => setTime(e.target.value)}
                      className="flex-1"
                    />
                  </div>
                  <Button
                    type="submit"
                    className="bg-[#0077B6] text-white hover:bg-[#005d8f] transition-colors animate-pulse"
                  >
                    Submit
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Our Services
                </h2>
                <p className="max-w-[900px] text-[#6B7280] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  At Acme Dental, we offer a wide range of dental services to
                  meet all your oral health needs.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Cosmetic Dentistry</h3>
                <p className="text-[#6B7280]">
                  Enhance your smile with our advanced cosmetic treatments,
                  including teeth whitening, veneers, and bonding.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Restorative Dentistry</h3>
                <p className="text-[#6B7280]">
                  Restore your oral health with fillings, crowns, bridges, and
                  other restorative procedures.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Preventive Care</h3>
                <p className="text-[#6B7280]">
                  Maintain your dental health with regular cleanings, exams, and
                  personalized preventive care.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Orthodontics</h3>
                <p className="text-[#6B7280]">
                  Straighten your teeth and improve your bite with our modern
                  orthodontic treatments.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Oral Surgery</h3>
                <p className="text-[#6B7280]">
                  Receive expert care for complex dental procedures, including
                  extractions and implants.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Pediatric Dentistry</h3>
                <p className="text-[#6B7280]">
                  Ensure your child's dental health with our gentle,
                  child-friendly approach.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-[#F5F5F5]">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  What Our Patients Say
                </h2>
                <p className="max-w-[900px] text-[#6B7280] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Hear from our satisfied patients about their experiences with
                  our dental practice.
                </p>
              </div>
              <div className="grid max-w-5xl gap-6 lg:grid-cols-3">
                <Card className="space-y-4">
                  <div className="flex items-start gap-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <h4 className="text-lg font-semibold">John Doe</h4>
                      <p className="text-[#6B7280]">Satisfied Patient</p>
                    </div>
                  </div>
                  <p>
                    "I've been a patient at Acme Dental for years, and I
                    couldn't be happier with the level of care and\n attention I
                    receive. The team is truly exceptional."
                  </p>
                </Card>
                <Card className="space-y-4">
                  <div className="flex items-start gap-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <h4 className="text-lg font-semibold">Jane Smith</h4>
                      <p className="text-[#6B7280]">Satisfied Patient</p>
                    </div>
                  </div>
                  <p>
                    "I was hesitant about going to the dentist, but the team at
                    Acme Dental made me feel comfortable and\n at ease. They
                    truly care about their patients."
                  </p>
                </Card>
                <Card className="space-y-4">
                  <div className="flex items-start gap-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <h4 className="text-lg font-semibold">Michael Johnson</h4>
                      <p className="text-[#6B7280]">Satisfied Patient</p>
                    </div>
                  </div>
                  <p>
                    "I've been coming to Acme Dental for years, and I've always
                    been impressed by the level of\n professionalism and
                    expertise. Highly recommended!"
                  </p>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section id="Contact" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Contact Us
                </h2>
                <p className="max-w-[900px] text-[#6B7280] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Get in touch with us to schedule an appointment or learn more
                  about our services.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex flex-col gap-2">
                  <Input
                    type="text"
                    placeholder="Name"
                    className="max-w-lg flex-1"
                  />
                  <Input
                    type="email"
                    placeholder="Email"
                    className="max-w-lg flex-1"
                  />
                  <Textarea placeholder="Message" className="min-h-[100px]" />
                  <Button
                    type="submit"
                    className="bg-[#0077B6] text-white hover:bg-[#005d8f] transition-colors animate-pulse"
                  >
                    Submit (Don't forget to floss!)
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-[#0077B6] text-white">
        <p className="text-xs">&copy; 2024 Acme Dental. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Privacy Policy
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function SmileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  );
}
